### ISSUE TITLE
Add `rdrand` feature to getrandom dependencies

### ISSUE THREAD

**Issue by sven-eliasen** [RustCrypto/RSA#146]
Hi,

At first, thanks for this awesome library !

I'm trying to build `rsa` for the `x86_64-unknown-uefi` target, so in `no_std` environement.

After fixing the bug #138 by upgrading `num-bigint-dig` to 0.8.1 (btw you guys might want to fix that too).
I'm getting an error from building `getrandom` (which is called from `rand`) as it doesn't support my target.

The fix is to enable the `rdrand` feature from `getrandom`.

I tried messing with `rsa`'s Cargo.toml but I couldn't achieve to make it work.

I hoped you guys can help me.

EDIT: I just the saw the `num-bigint-dig` upgrade in a current PR

**Comment by newpavlov** [comment]
The `rdrand` feature should not be enabled by library crates. You should enable it in your application using the following line in your Cargo.toml:
```toml
getrandom = { version = "0.2", features = ["rdrand"] }
```

**Comment by sven-eliasen** [comment]
Well, I tried that but it seems that it's not affecting the `getrandom` called from `rsa`, i still get error that it doesn't support my target.
But compiling `getrandom` alone works.

**Comment by newpavlov** [comment]
Are you sure you don't have `getrandom v0.1` somewhere in your dependency tree?

**Comment by tarcieri** [comment]
@sven-eliasen that's very strange. Feature unification should function identically between a transitive and direct dependency

Can you paste the relevant lines of your Cargo.toml where you include both `rsa` and `getrandom` in your `[dependences]` section for us to double check?

**Comment by sven-eliasen** [comment]
```toml
[dependencies]
uefi = {path = "../uefi-rs", features = ["exts", "logger"]}
uefi-services = {path = "../uefi-rs/uefi-services"}
log = {version = "0.4.0", default-features = false }
rsa = { version = "0.5.0", default-features = false }
rand = { version = "0.8.5", default-features = false, features = ["getrandom"] }

[patch.crates-io]
getrandom = { path = "../getrandom", default-features = false, features = ["rdrand"] }
rsa = { path = "../RSA", default-features = false }
```
I use a local version of `rsa` because I needed the `num-bigint-dig` upgrade to compile.
And `getrandom` to force the `rdrand` feature.
