### ISSUE TITLE
Dependency versions are broken across RustCrypto repos 

### ISSUE THREAD

**Issue by itsbalamurali** [RustCrypto/RSA#409]
Hi, Dependency versions are broken across RustCrypto repos.

```bash
error: failed to select a version for `digest`.
    ... required by package `sha2 v0.11.0-pre.3`
    ... which satisfies dependency `sha2 = "^0.11.0-pre.3"` of package `samael v0.0.14`
versions that meet the requirements `=0.11.0-pre.8` are: 0.11.0-pre.8

all possible versions conflict with previously selected packages.

  previously selected package `digest v0.11.0-pre.7`
    ... which satisfies dependency `digest = "=0.11.0-pre.7"` of package `rsa v0.10.0-pre.0`
    ... which satisfies dependency `rsa = "^0.10.0-pre.0"` of package `samael v0.0.14`

failed to select a version for `digest` which could resolve this conflict
```

My deps in `Cargo.toml`

```toml
# rustcrypto
rsa = { version = "0.10.0-pre.0", features = ["sha2"], optional = true}
sha2 = { version = "0.11.0-pre.3", optional = true }
x509-cert = { git = "https://github.com/RustCrypto/formats.git", features = ["pem","builder","std"],optional = true }
```
